name: CI

on:
  push:
    branches:
    pull_request:  # Runs on all branches
    workflow_dispatch:  # Manual trigger

env:
  FOUNDRY_PROFILE: mainnet
  BNB_MAINNET_RPC_URL: ${{ secrets.BNB_MAINNET_RPC_URL }}
jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge fmt default
        env:
          FOUNDRY_PROFILE: default
        run: |
          forge fmt --check
        id: fmt_default

      - name: Run Forge fmt mainnet tests
        env:
          FOUNDRY_PROFILE: mainnet
        run: |
          forge fmt --check
        id: fmt_mainnet

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge mainnet units
        env:
          FOUNDRY_PROFILE: mainnet
        run: |
          FOUNDRY_PROFILE=mainnet forge test -vvv
        id: test_mainnet