name: Forge Tests

on: push

jobs:
  Forge-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Checkout submodules
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          make install

      - name: Mainnet Forge tests
        env:
          FOUNDRY_PROFILE: mainnet
          BNB_MAINNET_RPC_URL: ${{ secrets.BNB_MAINNET_RPC_URL }}
        run: make ci-test rpc=$BNB_MAINNET_RPC_URL